---

- name: Create node_expoter user.
  user:
    name: node_exporter
    shell: /bin/false  
    comment: "Node_exporter User"  
    createhome: no  
    system: yes 

- name: Download node_exporter archive with checksum url (sha256).
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter-1.0.1.linux-amd64.tar.gz
    checksum: sha256:3369b76cd2b0ba678b6d618deab320e565c3d93ccb5c2a0d5db51a53857768ae
#  https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz

- name: Unarchive prometheus.
  unarchive:
    src: /tmp/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy prometheus binarie.
  copy:
    src: /tmp/node_exporter-1.0.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: 0755
    remote_src: yes

- name: Copy node_exporter systemd.
  copy:
    src: node_exporter.service 
    dest: /etc/systemd/system/node_exporter.service

- name: Reload systemd daemon;
  systemd:
    daemon_reload: yes

- name: Start and enable node_exporter service.
  systemd:
    state: started
    enabled: yes
    name: node_exporter
